// clientes/livros-react/src/components/LivroLista.js
import React, { useState, useEffect } from "react";
import { ControleLivros } from "../controle/ControleLivros"
import { ControleEditora } from "../controle/ControleEditora"

function LinhaLivro(props) {
  const {livro, excluir, controleEditora} = props;
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);  
  
  return (
    <tr>
      <td>{livro.titulo}<br />
        <button className="btn btn-sm btn-danger" onClick={() => excluir(livro.codigo)}>
          Excluir
        </button>
      </td>
      <td>{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td></td>
      <td>
        <ul>{livro.autores.map((autor, index) => (<li key={index}>{autor}</li>))}</ul>
      </td>
    </tr>
  );
};

export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  
  const controleEditora = new ControleEditora();

  useEffect(() => {
    const controleLivro = new ControleLivros();
    controleLivro.obterLivros().then((livro) => setLivros(livro));
    const carregarLivros = async () => {
      const livrosCarregados = await controleLivro.obterLivros(); 
      setLivros(livrosCarregados);
      setCarregado(true);
    };
    if (!carregado) {
      carregarLivros();
    }
  }, [carregado]); 

  const excluir = async (codigo) => {
    const controleLivro = new ControleLivros();
    await controleLivro.excluir(codigo).then(() => setCarregado(false));
  };
  
  return (
    <main className="container">
      <h1 className="text-start">Catálogo de Livros</h1>
      <table className="table table-striped">
        <thead className="table-dark text-start"> 
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th></th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody className="text-start">
          {Array.isArray(livros) && livros.length > 
          0 ? (
            carregado && livros.map((livro, index) => (
              <LinhaLivro
                key={index}
                livro={livro}
                excluir={excluir}
                controleEditora={controleEditora}
              />
            ))
          ) : (
            <tr>
              <td colSpan={5}>Nenhum livro encontrado.</td>
            </tr>
          )}
        </tbody>
      </table>
    </main>
  );
};

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../editora';
import Livro from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    })
  }

  excluir(codigoLivro: string): void {
    this.servLivros.excluir(codigoLivro).then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      });
    });
  }

  obterNome(codEditora: number) {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class="container">
  <h1 class="text-start">Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table-dark text-start">
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody class="text-start">
      <ng-container *ngIf="livros.length > 0; else noBooks">
        <tr *ngFor="let livro of livros; let i = index">
          <td>{{ livro.titulo }}<br/>
            <button class="btn btn-sm btn-danger" (click)="excluir(livro.codigo)">
              Excluir
            </button>
          </td>
          <td>{{ livro.resumo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </ng-container>
      <ng-template #noBooks>
        <tr>
          <td colspan="5">Nenhum livro encontrado.</td>
        </tr>
      </ng-template>
    </tbody>
  </table>
</main>
