// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import Livro from '../livro';
import Editora from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('', 2, "", "", ['', '']);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}

<main class="container">
  <h1>Dados do Livro</h1>
  <form ng (submit)="incluir()" ngNativeValidate="true">

    <div class="form-group mb-3">
      <label for="titulo">Título:</label>
      <input type="text" id="titulo" name="titulo" class="form-control" [(ngModel)]="livro.titulo" required="input">
    </div>

    <div class="form-group mb-3">
      <label for="resumo">Resumo:</label>
      <textarea name="resumo" id="resumo" class="form-control" [(ngModel)]="livro.resumo" required></textarea>
    </div>

    <div class="form-group mb-3">
      <label for="editora">Editora:</label>
      <select name="editora" id="editora" class="form-control" [(ngModel)]="livro.codEditora" required>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group mb-3">
      <label for="autores">Autores (um por linha):</label>
      <textarea name="autores" id="autores" class="form-control" [(ngModel)]="autoresForm" required=""></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Incluir Livro</button>
  </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import React, { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Menu } from '@/componentes/Menu';
import { useRouter } from 'next/router';
import ControleEditora from '@/classes/controle/ControleEditora';
import Livro from '@/classes/modelo/Livro';

const LivroDados: React.FC = () => {
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(0);
    const navigate = useRouter();
    const controleEditora: ControleEditora = new ControleEditora();
    const baseURL = 'http://localhost:3000/api/livros';

    const getEditoras = controleEditora.getEditoras.bind(controleEditora);

    const opcoes = getEditoras().map((editora) => {
        return { value: editora.codEditora, text: editora.nome };
    });

    function tratarCombo(event: React.ChangeEvent<HTMLSelectElement>) {
        const selectedCodEditora = Number(event.target.value);
        setCodEditora(selectedCodEditora);
    };

    async function incluirLivro(event: React.FormEvent<HTMLFormElement>) {
        event.preventDefault();
        const novoLivro: Livro = {
            codigo: "",
            codEditora: codEditora,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split('\n'),
        };

        const response = await fetch(baseURL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(novoLivro),
        });
        if (response.ok) {
            navigate.push('/LivroLista');
        }
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Livros Next</title>
            </Head>

            <Menu />

            <main className={styles.main}>
                <form onSubmit={incluirLivro}>
                    <h2>Novo Livro</h2><br/>
                    <div className='mb-3'>
                        <label htmlFor="titulo" className='form-label'>
                            Título
                        </label>
                        <input 
                            type="text"
                            required
                            className='form-control'
                            id='titulo'
                            value={titulo}
                            onChange={(e) => setTitulo(e.target.value)} 
                        />
                    </div>
                    <div className='mb-3'>
                        <label htmlFor="resumo" className='form-label'>
                            Resumo
                        </label>
                        <textarea 
                            className='form-control'
                            required
                            id='resumo'
                            value={resumo}
                            onChange={(e) => setResumo(e.target.value)} 
                        ></textarea>
                    </div>
                    <div className='mb-3'>
                        <label htmlFor="editora" className='form-label'>
                            Editora
                        </label>
                        <select
                            className='form-control'
                            id='codEditora'
                            value={codEditora}
                            onChange={tratarCombo} 
                            required
                        >
                            {opcoes.map((opcao) => (
                                <option key={opcao.value} value={opcao.value}>
                                    {opcao.text}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div className='mb-3'>
                        <label htmlFor="autores" className='form-label'>
                            Autores (um por linha)
                        </label>
                        <textarea
                            className='form-control'
                            required
                            id='autores'
                            value={autores}
                            onChange={(e) => setAutores(e.target.value)} 
                        ></textarea>
                    </div>
                    <button type='submit' className='btn btn-primary'>
                        Salvar
                    </button>
                </form>
            </main>
        </div>
    );
};

export default LivroDados;
