// clientes/livros-react/src/components/LivroDados.js
import React, { useState } from "react";
import { ControleLivros } from "../controle/ControleLivros";
import { ControleEditora } from "../controle/ControleEditora";
import { useNavigate } from "react-router-dom";

const LivroDados = () => {

  const controleLivro = new ControleLivros();
  const controleEditora = new ControleEditora();

  const opcoes = controleEditora.getEditoras().map(editora => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [autores, setAutores] = useState('');
  const [codEditora, setCodEditora] = useState(opcoes.length > 0 ? opcoes[0].value : '');

  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();

    const autoresArray = autores.split('\n').map(autor => autor.trim());

    const novoLivro = {
      codigo: 0,
      titulo: titulo,
      resumo: resumo,
      autores: autoresArray,
      codEditora: codEditora,
    };

    controleLivro.incluir(novoLivro).then(() => {
      navigate('/livros');
    });
  };

  return (
    <main className='container'>
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir}>
        <div className='form-group mb-3'>
          <label htmlFor='titulo'>Título</label>
          <input 
            type='text'
            id='titulo'
            className='form-control'
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
          />
        </div>
        <div className='form-group mb-3'>
          <label htmlFor='resumo'>Resumo</label>
          <textarea 
            id='resumo'
            className='form-control'
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
          />
        </div>
        <div className='form-group mb-3'>
          <label htmlFor='editora'>Editora</label>
          <select 
            id='editora'
            className='form-control'
            value={codEditora}
            onChange={tratarCombo}
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
            </select>
        </div>
        <div className='form-group mb-3'>
          <label>Autores (um por linha)</label>
          <textarea 
            id='autores'
            className='form-control'
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
          />
        </div>
        
        <button type='submit' className='btn btn-primary'>
          Salvar Dados
        </button>
      </form>
    </main>
  );
};

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import Livro from '../livro';
import Editora from '../editora';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro('', 2, "", "", ['', '']);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    });
  }
}

<main class="container">
  <h1>Dados do Livro</h1>
  <form ng (submit)="incluir()" ngNativeValidate="true">

    <div class="form-group mb-3">
      <label for="titulo">Título:</label>
      <input type="text" id="titulo" name="titulo" class="form-control" [(ngModel)]="livro.titulo" required="input">
    </div>

    <div class="form-group mb-3">
      <label for="resumo">Resumo:</label>
      <textarea name="resumo" id="resumo" class="form-control" [(ngModel)]="livro.resumo" required></textarea>
    </div>

    <div class="form-group mb-3">
      <label for="editora">Editora:</label>
      <select name="editora" id="editora" class="form-control" [(ngModel)]="livro.codEditora" required>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group mb-3">
      <label for="autores">Autores (um por linha):</label>
      <textarea name="autores" id="autores" class="form-control" [(ngModel)]="autoresForm" required=""></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Incluir Livro</button>
  </form>
</main>
